---
title: "Summary for Annual Report"
output: html_notebook
---

Summary of the 2020 data for the annual report.

# Load Packages

```{r}
library(tidyverse)
library(here)
library(readxl)
library(lubridate)
```

# Load Data
Use the import data script to bring the data in. 
Then run the rest.


Load the BHC names
```{r}
BHC_lookup <- read_xlsx(here("point_counts", "data_reference", 
                             "BHClookup.xlsx"))
```


# Survey Summary

Number of songbird point count stations and surveys conducted in 2021 by bird habitat class.
```{r}
surveys_out <- surveys %>% 
  left_join(stations, "StationID") %>%
  filter(Year == "2021") %>% 
  left_join(BHC_lookup, "BHC20") %>% 
  group_by(`Bird Habitat Class`, Sort) %>% 
  summarise(stations = n_distinct(StationID),
            surveys = n()) %>% 
  arrange(Sort)

# write_csv(surveys_out, here("point_counts", "out", "survey_count_2021.csv"))

```

# Species Tally

Make list of songbirds to filter data on:

```{r message=FALSE}
song_list <- 
  BCbirds %>%
  filter(IsSongbird == TRUE)
```


```{r}
species_tally <- 
  obs %>% 
  left_join(stations, "StationID") %>% 
  filter(Year == "2021") %>% 
#  filter(SpCode %in% song_list$SpCode) %>% 
  group_by(SpCode) %>% 
  summarize(`Survey Detections` = sum(Count),
            `Incidental Detections` = sum(Flyovers)) %>% 
  left_join(BCbirds, "SpCode") %>% 
  mutate(Songbird = if_else(IsSongbird == TRUE, "Yes", ""),
         `Incidental Detections` = replace_na(`Incidental Detections`, 0)) %>% 
  select(sort, Songbird, `English Name`, `Scientific Name`, `BC List`, COSEWIC, 
         `SARA Status`, `Survey Detections`, `Incidental Detections`) %>% 
  arrange(sort) %>% 
  select(!sort)

write_csv(species_tally, here("point_counts", "out", "species_tally_2021.csv"))
```

# Station Info
```{r}
station_tally <- stations %>% 
  left_join(surveys, "StationID") %>% 
  filter(Year == "2021") %>% 
  mutate(Time = format(Time, "%H:%M")) %>% 
  pivot_wider(StationID, names_from = Visit, values_from = c(Date, Time)) %>% 
  left_join(stations, "StationID") %>% 
  mutate(`UTM Zone` = "10") %>% 
  left_join(BHC_lookup, "BHC20") %>% 
  select(StationID, "UTM Zone", "UTM Easting" = Easting, "UTM Northing" = Northing,
         "Survey 1 Date" = Date_1, "Survey 1 Time" = Time_1, 
         "Survey 2 Date" = Date_2, "Survey 2 Time" = Time_2,
         `Bird Habitat Class`)

write_csv(station_tally, here("point_counts", "out", "station_tally_2021.csv"))
```

